# Jekyll config
exclude:  [Gemfile, Gemfile.lock, Guardfile, Rakefile, README.md]
lsi:      false
markdown: kramdown
paginate: 5
plugins: [jekyll-gist, jekyll-paginate, jekyll-sitemap]
#permalink: pretty
highlighter: rouge
source:   .

# site specific

copyright: "Copyright 2023 Matt Weppler | All Rights Reserved."

contact-info:
  email: matt@weppler.me

url: "https://matt.weppler.me"

navigation-header:
  - href:  /index.html
    link:  Home
    local: true
  - href:  /last-timer.html
    link:  LastTimer App
    local: true
  - href:  /projects.html
    link:  Projects
    local: true
  - href:  /resume.html
    link:  Resume
    local: true

navigation-footer:
  - class: icon-facebook-sign
    extra:
    href:  "https://www.facebook.com/matt.weppler.5"
    link:  Facebook
    local: false
  - class: "fa fa-instagram fa-inverse"
    extra:
    href:  "https://www.instagram.com/mweppler/"
    link:  Instagram
    local: false
  - class: icon-github-sign
    extra:
    href:  "https://github.com/mweppler"
    link:  github
    local: false
  - class: icon-linkedin-sign
    extra:
    href:  "https://www.linkedin.com/in/mweppler"
    link:  LinkedIn
    local: false
  - class: icon-twitter-sign
    extra:
    href:  "https://twitter.com/mattweppler"
    link:  Twitter
    local: false

javascripts:
  #- name: live-reload
    #script: |
      #<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
  - name: jquery-1.7.1-cdn
    script: |
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  - name: jquery-1.7.1-fallback
    script: |
      <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.1.min.js"><\/script>')</script>
  - name: plugins
    script: |
      <script src="/js/plugins.js?v=1"></script>
  - name: application
    script: |
      <script src="/js/script.js"></script>
  - name: layer-slider
    script: |
      <script type="text/javascript">
        $(document).ready(function(){
          $('#layerslider').layerSlider({
            skinsPath : '/css/layerslider/',
            skin : 'powerful'
          });
        });
      </script>
  - name: google-analytics
    script: |
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-YFEDSVQBPH"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-YFEDSVQBPH');
      </script>

stylesheets:
  - name: style
    stylesheet: |
      <link rel="stylesheet" href="/css/style.css">
  - name: forkawesome
    stylesheet: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/css/fork-awesome.min.css" integrity="sha256-XoaMnoYC5TH6/+ihMEnospgm0J1PM/nioxbOUdnM8HY=" crossorigin="anonymous">
