source:    .
pygments:  true
lsi:       false
exclude:   [Gemfile, Gemfile.lock, Guardfile, Rakefile, README.md]

copyright: "Copyright 2013 Matt Weppler | All Rights Reserved."

contact-info:
  email: matt@weppler.me

header-navigation:
  - href:  /index.html
    link: Home
  - href:  /projects.html
    link: Projects
  - href:  /resume.html
    link: Resume

footer-navigation:
  - class: icon-facebook-sign
    href:  "https://www.facebook.com/mattweppler"
    link:  Facebook
  - class: icon-github-sign
    href:  "https://github.com/mweppler"
    link:  github
  - class: icon-google-plus-sign
    href:  "https://plus.google.com/108656258437565935806?rel=author"
    link:  Google+
  - class: icon-linkedin-sign
    href:  "https://www.linkedin.com/in/mweppler"
    link:  LinkedIn
  - class: icon-pinterest-sign
    href:  "https://pinterest.com/mattweppler"
    link:  Pinterest
  - class: icon-twitter-sign
    href:  "https://twitter.com/mattweppler"
    link:  Twitter

javascripts:
  #- name: live-reload
    #script: |
      #<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
  - name: jquery-1.7.1-cdn
    script: |
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  - name: jquery-1.7.1-fallback
    script: |
      <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.1.min.js"><\/script>')</script>
  - name: plugins
    script: |
      <script src="/js/plugins.js?v=1"></script>
  - name: application
    script: |
      <script src="/js/script.js"></script>
  - name: layer-slider
    script: |
      <script type="text/javascript">
        $(document).ready(function(){
          $('#layerslider').layerSlider({
            skinsPath : '/css/layerslider/',
            skin : 'powerful'
          });
        });
      </script>
  - name: google-analytics
    script: |
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-41664436-1', 'weppler.me');
        ga('send', 'pageview');

      </script>

stylesheets:
  - name: style
    stylesheet: |
      <link rel="stylesheet" href="/css/style.css">
